### ISSUE TITLE
获取书籍章节列表报Internal Server Error错误

### ISSUE THREAD

**Issue by RenYanlong** [xiadd/zhuishushenqi#12]

**Comment by xiadd** [comment]
请给出报错的接口地址

**Comment by RenYanlong** [comment]
获取api文档中给出的示例：http://novel.juhe.im/book-chapters/56f8da09176d03ac1983f6cd会返回章节列表，但是替换书籍id后就会返回Internal Server Error，如https://novel.juhe.im/book-chapters/53e56ee335f79bb626a496c9

**Comment by xiadd** [comment]
确认后面id是书源的id，流程是这样的
通过书籍id获取书源id，再通过书源id获取章节列表。
切换书源也是这么操作。不是替换书籍id
