### ISSUE TITLE
关于API使用的问题

### ISSUE THREAD

**Issue by Hzzone** [xiadd/zhuishushenqi#2]
获取章节目录，章节内容
例如按照您的例子：```http://novel.juhe.im/author-books?author=忘语```
得到一本书的bookid是```567d2cb9ee0e56bc713cb2c0```
当我获取章节目录：```http://novel.juhe.im/book-chapters/567d2cb9ee0e56bc713cb2c0```
返回是```{"code":-1,"message":"Request failed with status code 404"}```
以上都是在浏览器中，获取章节目录同理。
请问这是什么原因呢？

**Comment by Hzzone** [comment]
实在太抱歉了...我搞混了，没看懂你的介绍

**Comment by xiadd** [comment]
1. 获取书籍id
2. 通过id获取书源
3. 选取书源通过书源id获取章节目录
4. 通过目录里的章节id获取章节内容

**Comment by gdrpAPeng** [comment]
应该是服务器出了问题吧，早上还能用的，现在复制你的接口直接打开都没反应了

**Comment by xiadd** [comment]
@gdrpAPeng 服务器被墙了 晚点我看看

**Comment by Hzzone** [comment]
@xiadd 你好，追书神器 api 有点问题了，
```
http://chapter2.zhuishushenqi.com/chapter/http://book.my716.com/getBooks.aspx?method=content&bookId=47492&chapterFile=%E7%AC%AC115%E5%9B%9E%20%E6%83%91%E5%81%8F%E7%A7%81%E6%83%9C%E6%98%A5%E7%9F%A2%E7%B4%A0%E5%BF%97%20%E8%AF%81%E5%90%8C%E7%B1%BB%E5%AE%9D%E7%8E%89%E5%A4%B1%E7%9B%B8%E7%9F%A5115.txt&chinese
```
```JSON
{
    "ok": false,
    "message": "{\"ok\":false,\"code\":\"Status code Error 404\"}"
}
```
