### ISSUE TITLE
大佬，今天测试启动失败，找不到方法，请指教！

### ISSUE THREAD

**Issue by yunxi66** [xiadd/zhuishushenqi#24]
]# make build
docker-compose build
redis uses an image, skipping
nginx uses an image, skipping
Building web
Step 1/7 : FROM node:13-alpine
 ---> b01d82bd42de
Step 2/7 : RUN mkdir -p /home/app
 ---> Using cache
 ---> bed7fe3d5ce1
Step 3/7 : WORKDIR /home/app
 ---> Using cache
 ---> 8e1654132139
Step 4/7 : COPY . /home/app
 ---> Using cache
 ---> db8537ad7f2c
Step 5/7 : ENV NODE_ENV=production
 ---> Using cache
 ---> 0c7e43929ae6
Step 6/7 : RUN npm install
 ---> Running in 03c0a0d70ce6
npm ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR! request to https://registry.npmjs.org/axios failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-03-08T09_49_12_806Z-debug.log
ERROR: Service 'web' failed to build: The command '/bin/sh -c npm install' returned a non-zero code: 1
make: *** [Makefile:2: build] Error 1

**Comment by xiadd** [comment]
看着像国外npm源没法访问。将Dockerfile里`RUN npm install` 替换成 `RUN npm install --registry=https://registry.npm.taobao.org/`

**Comment by yunxi66** [comment]
多谢，试了 还是不行，放弃了！

xia <notifications@github.com> 于2020年3月8日周日 下午7:12写道：
