### ISSUE TITLE
楼主大大，我使用您的书籍详情接口，但出现了500 (Internal Server Error)状况，求大佬帮帮忙看看哪里出问题了

### ISSUE THREAD

**Issue by FangZhangGithub** [xiadd/zhuishushenqi#26]
楼主大大，我使用您的书籍详情接口，但出现了500 (Internal Server Error)状况，求大佬帮帮忙看看哪里出问题了，我是在微信小程序里编写代码的，拜托大佬了

![FWTQ9GKM1RW9H8EW`5(6DSS](https://user-images.githubusercontent.com/48782073/77519756-04ff4780-6ebb-11ea-9bdb-46a111550708.png)

**Comment by xiadd** [comment]
我看了一下是ip被封了，暂时爬不了了，建议可以自己部署一下，我暂时没时间处理，后面会想办法解决
