### ISSUE TITLE
楼主，我使用您的书籍详情接口https://novel.juhe.im/book/{id}，但出现了500 (Internal Server Error)状况，

### ISSUE THREAD

**Issue by FangZhangGithub** [xiadd/zhuishushenqi#27]
楼主，我使用您的书籍详情接口https://novel.juhe.im/book/{id}，但出现了500 (Internal Server Error)状况，

**Comment by FangZhangGithub** [comment]
@xiadd

**Comment by xiadd** [comment]
我看了一下是ip被封了，暂时爬不了了，建议可以自己部署一下，我暂时没时间处理，后面会想办法解决
