### ISSUE TITLE
解密vip内容

### ISSUE THREAD

**Issue by BoneAsh** [xiadd/zhuishushenqi#3]
普通的文章都是明文显示的，而vip章节都是加密的，希望早日给出解密脚本

示例网页：http://novel.juhe.im/chapters/http%3A%2F%2Fvip.zhuishushenqi.com%2Fchapter%2F56f8da2c176d03ac1983fd88%3Fcv%3D1486473052632

**Comment by xiadd** [comment]
没法做到这一点，追书的每个章节解密token都是不一样的，而且这样做肯定严重侵权，目前可以通过换源做到获取章节内容

**Comment by lzpong** [comment]
换源怎么做呢，`http://api.zhuishushenqi.com/atoc?view=summary&book=:id`之后获取的id好像不是bookid呀

**Comment by xiadd** [comment]
@lzpong 获取的是书源id 通过书源id可以获取章节

**Comment by gdrpAPeng** [comment]
好像获取章节的api用不了了

**Comment by leeue14** [comment]
这个api会被封掉不，

**Comment by apem789** [comment]
今日2018年7月11日 这个api被封了?换了几个ip访问都获取不打数据了。凉凉~~~
 http://novel.juhe.im/category-info?gender=press&type=hot&major=%E4%BC%A0%E8%AE%B0%E5%90%8D%E8%91%97&minor=&start=0&limit=20 
createError.js:16 Uncaught (in promise) Error: Network Error
    at createError (createError.js:16)
    at XMLHttpRequest.handleError (xhr.js:87)

**Comment by xiadd** [comment]
@apem789 迁移服务器
