### ISSUE TITLE
今天接口不能使了，是服务停掉了吗

### ISSUE THREAD

**Issue by heliang0915** [xiadd/zhuishushenqi#7]
今天接口不能使了，是服务停掉了吗

**Comment by xiadd** [comment]
在迁移服务器

**Comment by xiadd** [comment]
@heliang0915 已修复 https暂时不能用

**Comment by heliang0915** [comment]
感谢，另外我看到 代码部署中 有一段 npm run build: 通过babel打包 这个命令 在package.json中没有

**Comment by xiadd** [comment]
@heliang0915 已经不需要打包这个过程了 node -r esm server.js可以直接运行
