### ISSUE TITLE
获取章节内容出错Internal Server Error

### ISSUE THREAD

**Issue by jimliang** [xiadd/zhuishushenqi#8]
> Internal Server Error

https://novel.juhe.im/chapters/http%3A%2F%2Fwww.biquge.la%2Fbook%2F17191%2F10604058.html

http://chapter2.zhuishushenqi.com/chapter/http%3A%2F%2Fwww.biquge.la%2Fbook%2F17191%2F10604058.html

**Comment by xiadd** [comment]
等我晚上修复

**Comment by xiadd** [comment]
测试了一下 发现有时候是可以打开的
![image](https://user-images.githubusercontent.com/8351437/45814356-f2c1ad80-bd07-11e8-85d1-eb5b775d4c36.png)
直接打开网站的话, 发现是备案掉了, 具体我还需要观察一下
